# CMake finder for NLopt

FIND_PATH(NLOPT_INCLUDE_DIRS nlopt.h)

SET (NLOPT_LIBNAMES nlopt nlopt_cxx)
FIND_LIBRARY (NLOPT_LIBRARY NAMES ${NLOPT_LIBNAMES})

INCLUDE (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (NLOPT DEFAULT_MSG NLOPT_LIBRARY NLOPT_INCLUDE_DIRS)

IF(NLOPT_FOUND)
  SET (NLOPT_LIBRARIES ${NLOPT_LIBRARY})
ELSE (NLOPT_FOUND)
  SET (NLOPT_LIBRARIES)
ENDIF (NLOPT_FOUND)

MARK_AS_ADVANCED (NLOPT_LIBRARY NLOPT_INCLUDE_DIR)

